name: flutter_webrtc_voice
description: A new Flutter project bootstrabep by cg_starter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_i18n: 0.22.3
  equatable: 2.0.0
  flutter_conditional_rendering: 2.0.0
  flutter_bloc: 7.0.0
  device_preview: 0.7.1
  json_annotation: 4.0.1
  simple_animations: 3.1.1
  flutter_screenutil: 5.0.0
  shimmer: 2.0.0
  gap: 2.0.0
  fluttertoast: 8.0.6
  connectycube_sdk: 2.0.0-nullsafety.3
  cg_extensions:
    git:
      url: https://github.com/Code-Growers/cg_extensions.git
      ref: null_safety
  lognito:
    git:
      url: https://github.com/Code-Growers/lognito
      ref: null_safety

dev_dependencies:
  build_runner: 2.0.2
  json_serializable: 4.1.1
  cg_analysis:
    git:
      url: https://github.com/Code-Growers/cg_analysis.git
      ref: master

flutter:
  uses-material-design: true
  assets:
    - lib/env/
    - i18n/en/
